### ISSUE TITLE
Image link doesn't work

### ISSUE THREAD

**Issue by Userr017** [OPMerchantServices/op-payment-service-for-magento-2#10]
No extension main logo available in checkout.

Link: https://cdn2.hubspot.net/hubfs/2610868/op-financial-group.svg (404 Not Found)

app/code/Op/Checkout/view/frontend/web/template/payment/checkout-bypass.html

**Comment by loueranta** [comment]
Sorry about this, the image resource has been fixed now.

**Comment by Userr017** [comment]
Thanks. Can you still add to checkout page someone name for this payment method? 

It is now just logo.

![kassa](https://user-images.githubusercontent.com/26794034/68584441-3d603500-0488-11ea-8f10-d7392478549b.png)

**Comment by loueranta** [comment]
Definitely, there should be text also. Our old logo had text in it, so that's why it's missing now after we changed the brand. Will fix this asap.

**Comment by Userr017** [comment]
I also recommend fix the logo size to default Magento 2 order invoice.
![email_logo](https://user-images.githubusercontent.com/26794034/68616417-aa49ee00-04cd-11ea-82e2-97e8c7feb7aa.JPG)

**Comment by loueranta** [comment]
Sure thing, we will fix this as well.

**Comment by loueranta** [comment]
@Userr017: These issues were resolved in the latest release

**Comment by Userr017** [comment]
Thanks for the fixes. One thing more, logo image first and then text but it is your choice if you make this change.

Now: 
![now](https://user-images.githubusercontent.com/26794034/70944342-8a24c600-205b-11ea-8d40-91890e83af29.png)

My idea:
![new](https://user-images.githubusercontent.com/26794034/70944376-9c9eff80-205b-11ea-8a4c-2ae7e9dde4db.png)

**Comment by loueranta** [comment]
Thanks for the suggestion. We will consider this next time we make changes to the UI. 👍
