### ISSUE TITLE
Possible issue in 1.1.7 where order success goes to cart.

### ISSUE THREAD

**Issue by sofokus-jali-rainio** [OPMerchantServices/op-payment-service-for-magento-2#116]
We're experiencing an issue in 1.1.7 where after the customer returns from the payment portal to Magento, they are not redirected to `checkout/onepage/success` but actually to `checkout/cart` with the error message `Order processing has been aborted. Please contact customer service.`

This could be due to some issue with our setup, but as far as I can tell this happens because 1.1.7 introduces changes to `app/code/Op/Checkout/Controller/Receipt/Index.php` and adds the line `$this->_redirect('checkout/cart')` to the end of the file. 

The issue seems to be that this line is always executed, even if the customer makes a successful purchase and the success redirect is executed on line `app/code/Op/Checkout/Controller/Receipt/Index.php:136`. Since `\Magento\Framework\App\Action\Action::_redirect` doesn't actually stop the code from progressing, the program first sets the redirect as `checkout/onepage/succcess`  but then immediately after it overrides it and sets it to `checkout/cart`. Adding an empty `return` statement after `$this->_redirect('checkout/onepage/success');` seems to fix the issue.

**Comment by roopesalminen** [comment]
@sofokus-jali-rainio Thank you for reporting this issue. We have created a fix for this in the newest 1.1.8 release.
