### ISSUE TITLE
PHP 7.4 support?

### ISSUE THREAD

**Issue by kunzi** [OPMerchantServices/op-payment-service-for-magento-2#128]
Trying to install this to server with php7.4 (Magento 2.4.0), but it's throwing this:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for op-merchant-services/op-payment-service-for-magento-2 1.2.2 -> satisfiable by op-merchant-services/op-payment-service-for-magento-2[1.2.2].
    - op-merchant-services/op-payment-service-for-magento-2 1.2.2 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.10) does not satisfy that requirement.

**Comment by adam-hrin-solteq** [comment]
Hello!

This issue has been fixed in the latest release https://github.com/OPMerchantServices/op-payment-service-for-magento-2/releases/tag/v1.2.3

-Adam
