### ISSUE TITLE
Broken image url for OP Tililuotto

### ISSUE THREAD

**Issue by nukka** [OPMerchantServices/op-payment-service-for-magento-2#136]
**Describe the bug**
The url for OP Tililuotto logo seems to be broken at checkout page. 

**To Reproduce**
Go to checkout page with Op Payment Service payment method enabled. Broken image is in the div element called "checkout-payment-method-op-tililuotto4".

**Screenshots**
https://i.imgur.com/qN4o5uD.png

**Comment by loueranta** [comment]
Thanks for reporting! 

That payment method is still in development and should not be visible on the test account. We have disabled it now.
