### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by PandaTawer3** [OPMerchantServices/op-payment-service-for-magento-2#146]
https://github.com/OPMerchantServices/op-payment-service-for-magento-2/blob/c924cd9713721e96128acf025041c83eef046769/Helper/Version.php#L46

Here you have usage of $this->curlClient but it doesn't add to the construct, so you cannot open the tab in the admin panel with the payment method. It just gives you a white page.

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @PandaTawer3. Thanks for noticing. We are pushing fix shortly. I will inform when fix is in github, it will come to other places with delay.

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @PandaTawer3. Fix is now published to github https://github.com/OPMerchantServices/op-payment-service-for-magento-2/releases/tag/v1.2.4.1

**Comment by PandaTawer3** [comment]
I think now, you can close this issue.

**Comment by Seppo-Konttinen-Solteq** [comment]
Ok closing now. Just for information, due to limitations of version numbers in Magento marketplace, we released new version which is identical to v1.2.4.1 tho.

https://github.com/OPMerchantServices/op-payment-service-for-magento-2/releases/tag/v1.2.5
