### ISSUE TITLE
Add Magento requirements to composer.json

### ISSUE THREAD

**Issue by juhanihaapala** [OPMerchantServices/op-payment-service-for-magento-2#23]
Readme says:
`This module works on Magento 2.2.7< and 2.3.0< {community|commerce} versions.`
If there is such requirement add them to composer.json (and possible others too).

**Comment by loueranta** [comment]
@juhanihaapala You are right, we should update the composer.json to reflect these requirements.
We'll fix it on the next release.

**Comment by pomppa** [comment]
On the Marketplace tools it states that Magento versions should not be required as dependencies: 
https://github.com/magento/marketplace-tools/blob/master/validate_m2_package.php#L50

I validated it, and it actually throws an error:
`ERROR - "checkout.zip": The 'magento/product-community-edition' package must not be specified as a dependency.`

So I would say we shouldn't add the requirements. Maybe the README.md should be updated to state that this has been tested with Magento 2.2.7< and 2.3.0< {community|commerce} versions.

**Comment by loueranta** [comment]
@pomppa Okay, let's update the info on the README.md instead as you suggested.
