### ISSUE TITLE
Using a coupon code while paying with Op_Checkout causes an internal server error

### ISSUE THREAD

**Issue by oskarolaussen** [OPMerchantServices/op-payment-service-for-magento-2#24]
This is most likely caused by private property $taxHelper not being set in constructor.
public function __construct(
        LoggerInterface $log,
        Signature $signature,
        UrlInterface $urlBuilder,
        RequestInterface $request,
        Json $json,
        CountryInformationAcquirerInterface $countryInformationAcquirer,
        TaxHelper $taxHelper,
        Order $order,
        RequestLogger $requestLogger,
        ResponseLogger $responseLogger,
        CheckoutHelper $helper,
        Config $resourceConfig,
        ModuleListInterface $moduleList
    ){
        $this->log = $log;
        $this->signature = $signature;
        $this->urlBuilder = $urlBuilder;
        $this->request = $request;
        $this->json = $json;
        $this->countryInfo = $countryInformationAcquirer;
        $this->order = $order;
        $this->requestLogger = $requestLogger;
        $this->responseLogger = $responseLogger;
        $this->helper = $helper;
        $this->resourceConfig = $resourceConfig;
        $this->moduleList = $moduleList;
    }

**Comment by loueranta** [comment]
@oskarolaussen Thanks for reporting! We will look in to this

**Comment by dominik-rohal-solteq** [comment]
@oskarolaussen Thank you for your finding. You are right, unset $taxHelper causes the error.

**Comment by loueranta** [comment]
@oskarolaussen This issue was fixed in the latest release: 
https://github.com/OPMerchantServices/op-payment-service-for-magento-2/releases/tag/v1.0.6
