### ISSUE TITLE
Errors in processInvoice are not logged

### ISSUE THREAD

**Issue by magulin** [OPMerchantServices/op-payment-service-for-magento-2#41]
We are experiencing a problem where 
1. Customer goes to payment provider from Magento checkout
2. Customer completes payment succesfully
3. Customer returns to Magento

Expected: Success page is shown
Actual: an error message is shown ("Unique constraint violation found") and the products are still in cart. Often customer tries to complete the order again, creating a duplicate order.

Biggest problem at the moment is that this error is not logged anywhere. So I cannot get a stack trace to see where this error originates, or even which orders are affected.

From a quick look this exception silencing happens in at least the function \Op\Checkout\Model\ReceiptDataProvider::processInvoice(). It catches all LocalizedExceptions, then throws a new CheckoutException with only the exception name. This exception message is then shown as an error message, but never logged.

Could the try/catch be removed from the processInvoice function? This is how processTransaction(), processPayment() and processOrder() already works.

**Comment by loueranta** [comment]
Thank you for reporting, we will look in to this.

**Comment by loueranta** [comment]
@magulin Our developer looked in to this:
> I have found an article about similar or the same problem. 
> https://magecomp.com/blog/fix-unique-constraint-violation-found-magento-2-checkout-after-migration/
> We do not know about any other store with similar problem. The problem might be in database data after magento version upgrade.
> I am going to find a way how to log more detailed logs.

**Comment by magulin** [comment]
The above article was not applicable in our case, but thanks anyway.

Seems like the "Unique constraint violation found" problem has not occurred after updating to version v1.0.7, so it was probably related to "Fixed issue with multiple callback URL calls when confirming payment". That would make sense as saving duplicate invoices could trigger this kind of database error.

This ticket is still valid though, as logging for processInvoice() is still missing.

**Comment by loueranta** [comment]
Thanks for the update

**Comment by loueranta** [comment]
@magulin The processInvoice() logging was added in the latest release (v1.2.4)
