### ISSUE TITLE
Changes to the extension

### ISSUE THREAD

**Issue by Userr017** [OPMerchantServices/op-payment-service-for-magento-2#47]
I hope you add the payment service provider name to "new order" email template. Now there is just the logo. It should have the same title what is added to extension configuration.

Now
![order_template](https://user-images.githubusercontent.com/26794034/73774628-fb941180-478c-11ea-8fb4-1c6c1f39a8c8.JPG)

Change example:
![order_template](https://user-images.githubusercontent.com/26794034/73773391-c4246580-478a-11ea-8b5f-dec49322262e.JPG)

Extension configuration:
![title](https://user-images.githubusercontent.com/26794034/73773514-f59d3100-478a-11ea-9269-20aa8ca590b7.jpg)

Second idea is change the logo position on the checkout page.

Now
![checkout](https://user-images.githubusercontent.com/26794034/73774270-5ed17400-478c-11ea-8d17-4193a97e2d0c.png)

Change
![checkout](https://user-images.githubusercontent.com/26794034/73774244-55e0a280-478c-11ea-9036-94806258b65e.JPG)

**Comment by roopesalminen** [comment]
Replaced payment provider logo with title in latest release.
