### ISSUE TITLE
Blank page after returning back to shop after payment

### ISSUE THREAD

**Issue by kunzi** [OPMerchantServices/op-payment-service-for-magento-2#78]
Just installed the extension to M 2.3.4. After making a test payment with test credentials I was redirected to a blank page with this kind of url:

/opcheckout/receipt/?checkout-account=375917&checkout-algorithm=sha256&checkout-amount=4490&checkout-stamp=31d11220fcc96b83d98a572a66f5e91f5b9acdd8065c8e54981cdf98d3a1a7e4&checkout-reference=1000016924&checkout-transaction-id=86405c66-79ca-11ea-814a-6330540c97f3&checkout-status=ok&checkout-provider=nordea&signature=8e8aeb9040cb7d5f51ed9a6961ed8f4ed34f4b18cc6534c97e49f359e47ab84d

**Comment by kunzi** [comment]
The solution to this was to change the status of the new order to Processing in the extension settings. For some reason we had that set as Pending. But I guess it should work when it's pending too?

**Comment by roopesalminen** [comment]
@kunzi Hello, we have started working on this issue. I will inform you when we have fixed the issue with 'Pending' status.

Thank you for reporting!

**Comment by roopesalminen** [comment]
@kunzi This has been fixed in the latest release version.
