### ISSUE TITLE
"No payment method selected. Please select one." when using Skip Bank Selection

### ISSUE THREAD

**Issue by sofokus-jali-rainio** [OPMerchantServices/op-payment-service-for-magento-2#85]
We're using this module for a new store and noticed an odd behavior. We can't get through the order process when Skip Bank Selection is active, because the frontend JS validation in `app/code/Op/Checkout/view/frontend/web/js/view/payment/method-renderer/opcheckout-method.js` fails consistently. I've tried looking around if something in our setup has broken this, but I can't find anything that suggests that.

We're using the latest version of this module, 1.1.2 and Magento 2.3.5. The issue has repeated on both the default Magento Checkout as well as Amasty's One Step Checkout. The issue was also on Magento 2.3.4.

The issue seems to start on row 156 on `opcheckout-method.js` where the validation checks `if (self.selectedPaymentMethodId() == 0)` which is always true for us because `selectedPaymentMethodId` never changes.

The only place where `selectedPaymentMethodId` is updated is `setPaymentMethodId()` which is only called when the observable `selectedMethodGroup` is updated. This observable should be updated when `selectPaymentMethod` is called, but at least on our setup, this does not happen because on row 120 it looks for `this.id` which is always undefined. Below is a screencap of the debugger on the line.

![image](https://user-images.githubusercontent.com/50737292/81790901-b3645800-950e-11ea-8890-e8980d9ceb72.png)
I assume `this` should have an ID of `opcheckout` but for some reason doesn't. At that moment, the value of `this` looks like this: 

```
UiClass {_super: undefined, ignoreTmpls: {…}, _requested: {…}, containers: Array(1), exports: {…}, …}
component: "Op_Checkout/js/view/payment/method-renderer/opcheckout-method"
containers: [UiClass]
dataScope: ""
displayArea: "payment-methods-items-default"
elems: ƒ observable()
exports: {}
extendProvider: true
hasUnique: undefined
ignoreTmpls: {templates: true, childDefaults: true}
imports: {}
index: "opcheckout"
item: {title: "Verkkopankki tai luottokortti", method: "opcheckout", __disableTmpl: {…}}
links: {}
listens: {}
maps: {imports: {…}, exports: {…}}
messageContainer: UiClass {_super: undefined, ignoreTmpls: {…}, errorMessages: ƒ, successMessages: ƒ}
modules: {storage: "localStorage"}
name: "checkout.steps.billing-step.payment.payments-list.opcheckout"
ns: "checkout"
parent: "checkout.steps.billing-step.payment.payments-list"
parentName: "checkout.steps.billing-step.payment.payments-list"
parentScope: ""
provider: ""
regions: {messages: ƒ}
registerNodes: true
source: undefined
statefull: {}
storage: ƒ ()
storageConfig: {provider: "localStorage", namespace: "checkout.steps.billing-step.payment.payments-list.opcheckout", path: "localStorage:checkout.steps.billing-step.payment.payments-list.opcheckout"}
template: "Op_Checkout/payment/checkout"
tracks: {}
_elems: [UiClass]
_requested: {localStorage: ƒ}
_super: undefined
__proto__: UiClass
```

**Comment by loueranta** [comment]
@sofokus-jali-rainio Thanks for reporting, we'll look in to this

**Comment by loueranta** [comment]
@sofokus-jali-rainio This bug was fixed in the latest release: https://github.com/OPMerchantServices/op-payment-service-for-magento-2/releases/tag/v1.1.3

**Comment by sofokus-jali-rainio** [comment]
@loueranta Thank you, everything seems to be working now
